# Generated by Django 3.2.16 on 2022-11-26 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('Agricultural Engineering', 'Agricultural Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Petroleum Engineering', 'Petroleum Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Food Engineering', 'Food Engineering'), ('Civil Engineering', 'Civil Engineering')], max_length=100)),
                ('level', models.CharField(choices=[('500 Level', '500 Level'), ('Spill Over', 'Spill Over')], default='500 Level', max_length=50)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
